---
title: "Customer Survey 1"
author: "Sidney Gerst, Corinna Hong"
date: "April 29, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(paletteer)

```

This markdown will combine the two customer surveys and compare existing customer answers with new customer answers. 

```{r}

#load in the customer data
new_customers <- read_csv("new_customer_survey1.csv")
old_customers <- read_csv("existing_customer_survey1.csv")

#add new identifer column to both dataframes before combining
new_customer_id <- new_customers %>%
  mutate(id = "new")

old_customer_id <- old_customers %>%
  mutate(id = "existing") %>%
  select(-X46)

#combine the dfs
all_customers <- bind_rows(new_customer_id, old_customer_id) %>%
  select(-feedback, -name) #get rid of columns w NAs (feedback and names), we don't care

```

```{r}

# Visualize known csf
total_survey_counts <- all_customers %>% 
  select(id) %>%
  group_by(id) %>% 
  summarize(total = length(id)) # total number of surveys for existing and new

csf_known_df <- all_customers %>% 
  select(known_csf, id) %>% 
  group_by(known_csf, id) %>% 
  summarize(count = length(known_csf)) # number who responded yes/no in existing and new

proportion_csf <- csf_known_df %>% 
  left_join(total_survey_counts, by = "id") %>% 
  mutate(proportion = count/324)

csf_bar <- ggplot(proportion_csf, aes(x = known_csf, y = proportion, fill = id)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "CSF Knowledge", y = "Proportion") +
  scale_fill_manual(name = "Customer Group", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) + # change legend name, color, and labels
  scale_y_continuous(expand = c(0,0)) +
  theme_classic()

csf_bar

```

```{r}

# Explore necessity between existing and new
necessary_df <- all_customers %>% 
  select(necessary_grocery, id) %>% 
  group_by(necessary_grocery, id) %>% 
  summarize(count = length(necessary_grocery)) # number who responded yes/sometimes/no in existing and new

proportion_necessary <- necessary_df %>% 
  left_join(total_survey_counts, by = "id") %>% 
  mutate(proportion = count/324)


necessary_bar <- ggplot(proportion_necessary, aes(x = necessary_grocery, y = proportion, fill = id)) + 
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(name = "Customer Group", labels = c("Existing", "New"), values = c("royalblue1", "seagreen")) +
  labs(x = "Necessity", y = "Proportion") +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic()

necessary_bar



# Explore necessity broken down by delivery counts
necessary_delivery_df <- all_customers %>% 
  select(necessary_grocery, delivery_count) %>% 
  group_by(necessary_grocery, delivery_count) %>% 
  summarize(necessary = length(necessary_grocery)) %>% # number of people who said yes/sometimes/no based on the # of deliveries they have received
  mutate(delivery_count = factor(delivery_count, levels = c("1-3", "4-6", "7-9","10 or more")))

proportion_necessary_delivery <- necessary_delivery_df %>% 
  mutate(proportion = necessary/324) # Divide by total # of surveys


necessary_delivery_bar <- ggplot(proportion_necessary_delivery, aes (x = delivery_count, y = proportion, fill = necessary_grocery)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Delivery Count", y = "Proportion") +
  scale_fill_manual(name = "Necessity", values = c("royalblue1", "seagreen","lightsalmon2")) + # change legend name and color
  theme_classic()

#values = c("pink2", "grey89","darkslategray3")
  

necessary_delivery_bar

```

```{r}

# Demographics
demo_df <- all_customers %>% 
  select(id, age, household_number,grocery_expenditure,income) %>%
  filter(age != "Rather not say")  # remove those who declined to state
 
demo_df$household_number <- as.numeric(demo_df$household_number)

summ_table <- demo_df %>% 
  summarize(mean_size = mean(household_number),
            median_size = median(household_number)) 

income <- all_customers %>%
  select(id, income) %>%
  group_by(id, income) %>%
  summarize(count_income = length(income)) %>%
  mutate(prop_income = count_income/324) %>%
  filter(income != "Rather not say")

income_chart <- ggplot(income, aes(x = income, y = prop_income, fill = id))+
  geom_bar(stat = "identity") +
  theme_classic()+
  scale_fill_manual(name = "Customer Group", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  scale_y_continuous(expand = c(0,0))+
  labs(x = "Income Range", y = "Proportion") +
  scale_x_discrete(limits = c("< $50K", "$50 - $100K", "$101 - $150K", "$151 - $200K", "$201 - $250K", "Over $250K"))

income_chart

income_chart_ppt <- ggplot(income, aes(x = income, y = prop_income))+
  geom_bar(stat = "identity", fill = "royalblue1") +
  theme_classic()+
  scale_y_continuous(expand = c(0,0))+
  labs(x = "Income Range", y = "Proportion") +
  scale_x_discrete(limits = c("< $50K", "$50 - $100K", "$101 - $150K", "$151 - $200K", "$201 - $250K", "Over $250K"))

income_chart_ppt


# Age Bar chart
age_bar <- ggplot(demo_df, aes(x = age, fill = id))+
  geom_histogram(stat = "count") +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Age", y = "Count") +
  scale_fill_manual(name = "Customer Group", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  theme_classic() 
age_bar



# Age pie chart
age_pie_df <- demo_df %>% 
  group_by(age) %>% 
  summarize(total = length(age)) %>%
  mutate(proportion = total/324) # calculate proportions

age_pie <- ggplot(age_pie_df, aes(x = "", y = total, fill = age)) +
  geom_bar(stat = "identity", width = 0.8, color = "white") +
  coord_polar("y", start = 0) + # turn this bar graph into a pie chart!
  theme_void() + # remove background, grid, and numberic labels
  scale_fill_manual(name = "Age", values = c("gray80", "seagreen","lightsalmon2", "plum2", "lightgoldenrod1", "royalblue1")) 

age_pie 



# Age proportions separated into new and existing
age_proportion_df <- demo_df %>% 
  group_by(age, id) %>% 
  summarize(count = length(age)) %>% 
  left_join(age_pie_df, by = "age") %>% 
  mutate(proportion = count/324) %>% 
  filter(age != "Rather not say") # remove those who declined to state

age_proportion_bar <- ggplot(age_proportion_df, aes(x = age, y = proportion, fill = id)) + 
  geom_bar(stat = "identity") +
  labs(x = "Age Range", y = "Proportion") +
  scale_fill_manual(name = "Customer Group", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic()

age_proportion_bar

```

**New vs Old customers**

```{r}
#visualize count
customer_count <- ggplot(all_customers, aes(x = id, fill = id))+
  geom_bar(stat = "count")+
  theme_classic()+
  scale_fill_manual(name = "Customer Group", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  theme(legend.position = "none")+
  scale_y_continuous(expand = c(0,0)) 

customer_count

#get proportion
customer_prop <- all_customers %>%
  select(id) %>%
  group_by(id) %>%
  summarize(count = length(id)) %>%
  mutate(prop = count/324)
  

#visualize prop
customer_prop_chart <- ggplot(customer_prop, aes(x = id, y = prop, fill = id)) +
  geom_bar(stat = "identity") +
  theme_classic()+
  scale_fill_manual(values = c("royalblue1", "seagreen"))+
  theme(legend.position = "none")+
  scale_y_continuous(expand = c(0,0))+
  labs(x = "Customer Group", y = "Proportion")+
  scale_x_discrete(breaks = c("existing", "new"), labels = c("Existing", "New"))


```



**Start looking at differences in what customers want grocery-wise**

```{r}

#Do you considered Get Hooked a core/necessary part of your weekly grocery supply?

grocery <- all_customers %>%
  select(id, necessary_grocery, grocery_influence, grocery_budget, grocery_expenditure, income)

#lets just look at all of it
necessary_grocery <- ggplot(grocery, aes(x = necessary_grocery, fill = id))+
  geom_bar(stat = "count")+
  facet_wrap(~id)+
  theme_classic()+
  scale_fill_manual(name = "Necessity", values = c("royalblue1", "seagreen","lightsalmon2")) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Grocery Necessity", y = "count")
  
necessary_grocery


#grocery influence
# Explore necessity broken down by influence counts
necessary_influence_df <- grocery %>% 
  select(id, necessary_grocery, grocery_influence) %>% 
  group_by(id, necessary_grocery, grocery_influence) %>% 
  summarize(necessary = length(necessary_grocery))

proportion_necessary_influence <- necessary_influence_df %>% 
  mutate(proportion = necessary/324) # Divide by total # of surveys


#How have recent changes to grocery access influenced your decision to join or continue with Get Hooked?
influence_grocery <- ggplot(proportion_necessary_influence, aes(x = necessary_grocery, y = proportion, fill = id))+
  geom_bar(stat = "identity")+
  facet_wrap(~grocery_influence)+
  theme_classic()+
  theme(axis.text.x = element_text(angle=15))+
  scale_fill_manual(name = "Customer ID", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Grocery Necessity", y = "Propotion")
  
influence_grocery





  

```

**Stay after Covid**

```{r}

#When the COVID-19 pandemic has passed, how likely are you to continue your Get Hooked membership?

covid_count_chart <- ggplot(all_customers, aes(x = covid_end, fill = id))+
  geom_bar(stat = "count")+
  theme_classic()+
  theme(axis.text.x = element_text(angle=11))+
  scale_fill_manual(name = "Customer ID", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "How likely to continue Get Hooked", y = "Count")

covid_count_chart

#look at the proportions
covid_propotion <- all_customers %>%
  select(id, covid_end) %>%
  group_by(id, covid_end) %>%
  summarize(covid_count = length(covid_end)) %>%
  mutate(proportion = covid_count/324)

covid_proportion_chart <- ggplot(covid_propotion, aes(x = covid_end, y = proportion, fill = id))+
  geom_bar(stat = "identity")+
  theme_classic()+
  #theme(axis.text.x = element_text(angle=11))+
  scale_fill_manual(name = "Customer ID", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "How likely to continue Get Hooked", y = "Proportion")

covid_proportion_chart


```



**Fair Price**

```{r}
#Do you feel you pay a fair price for your seafood subscription?

#counts
fair_price_count <- ggplot(all_customers, aes(x = fair_price, fill = id))+
  geom_bar(stat = "count", position = "dodge")+
  theme_classic()+
  scale_fill_manual(name = "Customer ID", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  scale_y_continuous(expand = c(0,0)) +
  theme(axis.text.x = element_text(angle=10.5))+
  labs(x = "Do you feel you pay a fair price for seafood?", y = "Count")

fair_price_count

#look at the proportions
fair_propotion <- all_customers %>%
  select(id, fair_price) %>%
  group_by(id, fair_price) %>%
  summarize(fair_count = length(fair_price)) %>%
  mutate(proportion = fair_count/324)

#LOOK AT IT
fair_price_propotion <- ggplot(fair_propotion, aes(x = fair_price, y = proportion, fill = id))+
  geom_bar(stat = "identity", position = "dodge")+
  theme_classic()+
  scale_fill_manual(name = "Customer ID", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_discrete(limits = c("It's overpriced", "It's a little overpriced", "Yes, it's fair", "It's worth more")) +
  #theme(axis.text.x = element_text(angle=10))+
  labs(x = "Do you feel you pay a fair price for seafood?", y = "Proportion")

fair_price_propotion



```

**Going to compare how likely people will continue with income and age**

```{r}


income_age <- all_customers %>%
  select(id, age, income, covid_end, grocery_influence) 


age_income_jitter <- ggplot(income_age, aes(x = age, y = income, color = covid_end))+
  geom_jitter(position = position_jitter(width = 0.1, height = 0.2), alpha = 0.8) +
  scale_y_discrete(limits = c("< $50K", "$50 - $100K", "$101 - $150K", "$151 - $200K", "$201 - $250K", "Over $250K", "Rather not say")) +
  scale_color_manual(name = "Likelihood", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Likely", "Not Sure", "Unlikely")) +
  labs(x = "Age", y = "Income") +
  theme_bw()


age_income_jitter

age_covid_jitter<- ggplot(income_age, aes(x = covid_end, y = age, color = covid_end))+
  geom_jitter(position = position_jitter(width = 0.1, height = 0.2)) +
  #scale_y_discrete(limits = c("< $50K", "$50 - $100K", "$101 - $150K", "$151 - $200K", "$201 - $250K", "Over $250K", "Rather not say")) +
  scale_color_manual(name = "Customer ID", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  labs(y = "Age", x = "Likelihood to continue") +
  theme_bw()

age_covid_jitter


income_covid_jitter <- ggplot(income_age, aes(x = covid_end, y = income, color = id))+
  geom_jitter(position = position_jitter(width = 0.1, height = 0.2), alpha = 0.5) +
  scale_y_discrete(limits = c("< $50K", "$50 - $100K", "$101 - $150K", "$151 - $200K", "$201 - $250K", "Over $250K", "Rather not say")) +
  scale_color_manual(name = "Customer ID", values = c("royalblue1", "seagreen"), labels = c("Existing", "New")) +
  labs(y = "Income", x = "Likelihood to continue")

income_covid_jitter


#regression?


```

Here is Allison's lab with multivariate regressions: https://github.com/allisonhorst/esm-206-labs-fall-2018/blob/master/lab_9/lab_9_key.Rmd