---
title: "retention_model"
author: "Corinna Hong"
date: "May 22, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(MASS)
library(effects)
```

```{r}

#load in the customer data
new_customers <- read_csv("new_customer_survey1.csv")
old_customers <- read_csv("existing_customer_survey1.csv")

#add new identifer column to both dataframes before combining
new_customer_id <- new_customers %>%
  mutate(id = "new")

old_customer_id <- old_customers %>%
  mutate(id = "existing") %>%
  dplyr::select(-X46)

#combine the dfs
all_customers <- bind_rows(new_customer_id, old_customer_id) %>%
  dplyr::select(-feedback, -name) #get rid of columns w NAs (feedback and names), we don't care

#Create a subset only for columns in model
customer_subset <- all_customers %>% 
  dplyr::select(covid_end, delivery_count, necessary_grocery, age, income, fair_price, id) %>%
  filter(income != "Rather not say")

```


### Market analysis to determine which variables influence the decision to continue, maybe continue, or not continue with Get Hooked subscription post COVID-19 SIP


*Ordinal logistic regression to predict the probability of staying with Get Hooked after COVID-19 based on delivery count, age, necessity, income, id

```{r}

#Set-Up

#Ordering the dependent variable
customer_subset$covid_end = factor(customer_subset$covid_end, levels = c("Unlikely to continue", "Not sure", "Likely to continue"), ordered = TRUE) 

#Ordering the independent variables
customer_subset$age = factor(customer_subset$age, levels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+"), ordered = TRUE)
customer_subset$delivery_count = factor(customer_subset$delivery_count, levels = c("1-3", "4-6", "7-9", "10 or more"), ordered = TRUE)
customer_subset$necessary_grocery = factor(customer_subset$necessary_grocery, levels = c("No, it is extra", "Sometimes", "Yes"), ordered = TRUE)
customer_subset$income = factor(customer_subset$income, levels = c("< $50K", "$50 - $100K", "$101 - $150K", "$151 - $200K", "$201 - $250K","Over $250K"), ordered = TRUE)
customer_subset$fair_price = factor(customer_subset$fair_price, levels = c("It's overpriced", "It's a little overpriced", "Yes, it's fair", "It's worth more"), ordered = TRUE)

```

```{r}

#Data Exploration


#Summarizing the data
summary(customer_subset)

#Making frequency table
table(customer_subset$covid_end, customer_subset$delivery_count) # more deliveries more likely to continue
table(customer_subset$covid_end, customer_subset$age) # likely to continue peaks at 25-45 age range
table(customer_subset$covid_end, customer_subset$necessary_grocery) # seen as a ncessity, more likley to continue
table(customer_subset$covid_end, customer_subset$income) # likely to continue peaks at $101-150K  
table(customer_subset$covid_end, customer_subset$id) # existing customers more likely to continue, new customers are more unsure
table(customer_subset$covid_end, customer_subset$fair_price)

```


```{r}

#Build the model!
model = polr(covid_end ~ delivery_count + age + necessary_grocery + income + id + fair_price, data = customer_subset)
summary(model)


#plot the model
plot(Effect(focal.predictors = c("delivery_count", "necessary_grocery"), model), main = "Effect Plot", 
     axes = list(x = list(lab = "Delivery Count")))

plot(Effect(focal.predictors = c("age", "income"), model), main = "Effect Plot", 
     axes = list(x = list(lab = "Delivery Count")))

e_grocery_delivery <- Effect(focal.predictors = c("necessary_grocery", "delivery_count", "age"), model)
e_grocery_delivery <- as.data.frame(e_grocery_delivery)

e_grocery_delivery_plot <- ggplot() +
  geom_line(e_grocery_delivery, mapping = aes(x = necessary_grocery, y = prob.Unlikely.to.continue, group = 1, color = "blue"), lwd=1.4) +
  geom_point(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Unlikely.to.continue)) +
  geom_line(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Not.sure, group = 1, color = "red"), lwd=1.4) +
  geom_point(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Not.sure)) +
  geom_line(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Likely.to.continue, group = 1, color = "green"), lwd=1.4) +
  geom_point(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Likely.to.continue)) +
  scale_color_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Unlikely", "Likely", "Not Sure"))+
  facet_wrap(~delivery_count) +
  theme_classic() +
  labs(x = "Is Get Hooked a Necessary Part of your Groceries", y = "Probability of Continuing with Get Hooked")

e_grocery_delivery_plot

#plot using ggplot
#income plot
e_income <- Effect(focal.predictors = "income", model )
e_income <- as.data.frame(e_income)

e_income_plot <- ggplot() +
  geom_line(e_income, mapping = aes(x = income, y = prob.Unlikely.to.continue, group = 1, color = "blue"), lwd=1.4) +
  geom_point(e_income, mapping = aes(x = income, y = prob.Unlikely.to.continue)) +
  geom_line(e_income, mapping = aes(x = income, y = prob.Not.sure, group = 1, color = "red"), lwd=1.4) +
  geom_point(e_income, mapping = aes(x = income, y = prob.Not.sure)) +
  geom_line(e_income, mapping = aes(x = income, y = prob.Likely.to.continue, group = 1, color = "green"), lwd=1.4) +
  geom_point(e_income, mapping = aes(x = income, y = prob.Likely.to.continue)) +
  scale_color_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Unlikely", "Likely", "Not Sure"))+
  theme_classic() +
  labs(x = "Income", y = "Probability of Continuing with Get Hooked")

e_income_plot

#age plot
e_age <- Effect(focal.predictors = "age", model)
e_age <- as.data.frame(e_age)

e_age_plot <- ggplot() +
  geom_line(e_age, mapping = aes(x = age, y = prob.Unlikely.to.continue, group = 1, color = "blue"), lwd=1.4) +
  geom_point(e_age, mapping = aes(x = age, y = prob.Unlikely.to.continue)) +
  geom_line(e_age, mapping = aes(x = age, y = prob.Not.sure, group = 1, color = "red"), lwd=1.4) +
  geom_point(e_age, mapping = aes(x = age, y = prob.Not.sure)) +
  geom_line(e_age, mapping = aes(x = age, y = prob.Likely.to.continue, group = 1, color = "green"), lwd=1.4) +
  geom_point(e_age, mapping = aes(x = age, y = prob.Likely.to.continue)) +
  scale_color_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Unlikely", "Likely", "Not Sure"))+
  theme_classic() +
  labs(x = "Age", y = "Probability of Continuing with Get Hooked")

e_age_plot


#delivery plot
e_delivery <- Effect(focal.predictors = "delivery_count", model)
e_delivery <- as.data.frame(e_delivery)

e_delivery_plot <- ggplot() +
  geom_line(e_delivery, mapping = aes(x = delivery_count, y = prob.Unlikely.to.continue, group = 1, color = "blue"), lwd=1.4) +
  geom_point(e_delivery, mapping = aes(x = delivery_count, y = prob.Unlikely.to.continue)) +
  geom_line(e_delivery, mapping = aes(x = delivery_count, y = prob.Not.sure, group = 1, color = "red"), lwd=1.4) +
  geom_point(e_delivery, mapping = aes(x = delivery_count, y = prob.Not.sure)) +
  geom_line(e_delivery, mapping = aes(x = delivery_count, y = prob.Likely.to.continue, group = 1, color = "green"), lwd=1.4) +
  geom_point(e_delivery, mapping = aes(x = delivery_count, y = prob.Likely.to.continue)) +
  scale_color_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Unlikely", "Likely", "Not Sure"))+
  theme_classic() +
  labs(x = "Delivery Count", y = "Probability of Continuing with Get Hooked")

e_delivery_plot


#necessary grocery
e_grocery <- Effect(focal.predictors = "necessary_grocery", model)
e_grocery <- as.data.frame(e_grocery)

e_grocery_plot <- ggplot() +
  geom_line(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Unlikely.to.continue, group = 1, color = "blue"), lwd=1.4) +
  geom_point(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Unlikely.to.continue)) +
  geom_line(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Not.sure, group = 1, color = "red"), lwd=1.4) +
  geom_point(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Not.sure)) +
  geom_line(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Likely.to.continue, group = 1, color = "green"), lwd=1.4) +
  geom_point(e_grocery, mapping = aes(x = necessary_grocery, y = prob.Likely.to.continue)) +
  scale_color_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Unlikely", "Likely", "Not Sure"))+
  theme_classic() +
  labs(x = "Is Get Hooked a Necessary Part of your Groceries", y = "Probability of Continuing with Get Hooked")

e_grocery_plot

```

```{r}

#Plot the model II - plots for presentation


#Grocery necessity bar graph
e_grocery_subset <-e_grocery %>% 
  dplyr::select(necessary_grocery:prob.Likely.to.continue) %>%
  gather(`prob.Unlikely.to.continue`, `prob.Not.sure`, `prob.Likely.to.continue`, key = "continue", value = "probability")

e_grocery_bar <- ggplot(e_grocery_subset, aes(fill = continue, x = necessary_grocery, y = probability)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual(values=c("royalblue1", "seagreen", "lightsalmon2", "royalblue1", "seagreen", "lightsalmon2", "royalblue1", "seagreen", "lightsalmon2")) +
  labs(x = "Grocery Necessity Perception", y = "Probability of Continuing with Get Hooked") +
  scale_y_continuous(expand = c(0,0)) +  
  scale_fill_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Likely", "Not Sure", "Unlikely"))+
  theme_classic()

e_grocery_bar


#Income bar graph
e_income_subset <- e_income %>%
  dplyr::select(income:prob.Likely.to.continue) %>% 
  gather(`prob.Unlikely.to.continue`, `prob.Not.sure`, `prob.Likely.to.continue`, key = "continue", value = "probability")
  
e_income_bar <- ggplot(e_income_subset, aes(fill = continue, x = income, y = probability)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual(values=c("royalblue1", "seagreen", "lightsalmon2", "royalblue1", "seagreen", "lightsalmon2", "royalblue1", "seagreen", "lightsalmon2")) +
  labs(x = "Income", y = "Probability of Continuing with Get Hooked") +
  scale_y_continuous(expand = c(0,0)) +  
  scale_x_discrete(limits = c("< $50K", "$50 - $100K", "$101 - $150K", "$151 - $200K", "$201 - $250K", "Over $250K")) +
  scale_fill_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Likely", "Not Sure", "Unlikely"))+
  theme_classic()

e_income_bar


#Delivery Bar Graph
e_delivery_subset <- e_delivery %>%
  dplyr::select(delivery_count:prob.Likely.to.continue) %>%
  gather(`prob.Unlikely.to.continue`, `prob.Not.sure`, `prob.Likely.to.continue`, key = "continue", value = "probability")

e_delivery_bar <- ggplot(e_delivery_subset, aes(fill =continue, x = delivery_count, y = probability )) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Likely", "Not Sure", "Unlikely"))+
  theme_classic() +
  scale_x_discrete(limits = c("1-3", "4-6", "7-9","10 or more")) +
  scale_y_continuous(expand = c(0,0)) + 
  labs(x = "Delivery Count", y = "Probability of Continuing with Get Hooked")

e_delivery_bar



#Age Bar Graph
e_age_subset <- e_age %>%
  dplyr::select(age:prob.Likely.to.continue) %>%
  gather(`prob.Unlikely.to.continue`, `prob.Not.sure`, `prob.Likely.to.continue`, key = "continue", value = "probability")

e_age_bar <- ggplot(e_age_subset, aes(fill = continue, x = age, y = probability)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Likely", "Not Sure", "Unlikely"))+
  theme_classic() +
  scale_y_continuous(expand = c(0,0)) + 
  labs(x = "Age", y = "Probability of Continuing with Get Hooked")

e_age_bar

#fair price bar graph
e_fair <- Effect(focal.predictors = "fair_price", model )
e_fair <- as.data.frame(e_fair)

e_fair_subset <- e_fair %>%
  dplyr::select(fair_price:prob.Likely.to.continue) %>%
  gather(`prob.Unlikely.to.continue`, `prob.Not.sure`, `prob.Likely.to.continue`, key = "continue", value = "probability")

e_fair_bar <- ggplot(e_fair_subset, aes(fill = continue, x = fair_price, y = probability))+
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual(name = "Likelihood to Continue", values = c("royalblue1", "seagreen", "lightsalmon2"), labels = c("Likely", "Not Sure", "Unlikely"))+
  theme_classic() +
  scale_y_continuous(expand = c(0,0)) + 
  labs(x = "Fair Price", y = "Probability of Continuing with Get Hooked")

e_fair_bar




```

